const testConstants = {
  GAME_SCORE_IDENTIFIER: "game_score",
  LOVE_ALL: "Love-All",
  FIFTEEN_LOVE: "Fifteen-Love",
  PLAYER_ONE: "Player One",
  PLAYER_TWO: "Player Two",
  THIRTY_LOVE: "Thirty-Love",
  FORTY_LOVE: "Forty-Love",
  LOVE_FIFTEEN: "Love-Fifteen",
  LOVE_THIRTY: "Love-Thirty",
  LOVE_FORTY: "Love-Forty",
  ZERO: 0,
  ONE_TIME: 1,
  TWO_TIMES: 2,
  THREE_TIMES: 3,
  FOUR_TIMES: 4,
  FIFTEEN_ALL: "Fifteen-All",
  THIRTY_ALL: "Thirty-All",
  DEUCE: "Deuce",
  PLAYER_ONE_ADVANTAGE: "Player One Advantage",
  PLAYER_TWO_ADVANTAGE: "Player Two Advantage",
  PLAYER_ONE_WIN: "Player One Win",
};

export { testConstants };
